{{ $namespace := required "namespace is a required value" .Values.namespace }}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: {{$namespace}}
spec:
  ports:
    - name: sonar
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonarqube
  type: ClusterIP