{{ $dbSonarqubePassword := required "dbSonarqubePassword is a required value" .Values.dbSonarqubePassword }}
{{ $namespace := required "namespace is a required value" .Values.namespace }}

apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{$namespace}}
type: Opaque
stringData:
  password: {{ $dbSonarqubePassword }}