sonarqube:
  db:
    dbName: sonarqube
    hostName: sonarqube
  image:
    name: sonarqube
    tag: 7.9.5
    pullPolicy: Always

smartFridge:
  db:
    dbName: smart-fridge
    hostName: smart-fridge
  image:
    name: smart-fridge-backend
    tag: latest
    pullPolicy: Always
    registry: registry.gitlab.com/master-intelligente-systeme/ise/smartfridge

namespace: dev